setwd("C:/Users/gerge/Desktop/ExData_Plotting1")
Data<-read.csv("household_power_consumption.txt",header = T,na.strings = "?",sep = ';',nrows =2075259,check.names = F,stringsAsFactors = F,comment.char = "",quote = '\"')
data1<-subset(Data,Date %in% c("1/2/2007","2/2/2007"))
datetime <-strptime(paste(data1$Date, data1$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
data1$Datetime<-as.POSIXct(datetime)

png("plot4.png",width = 480,height = 480)
par(mfrow=c(2,2))
plot(data1$Datetime,data1$Global_active_power,type="l", ylab="Global Active Power", xlab="")
plot(data1$Datetime,data1$Voltage,type="l", ylab="Voltage", xlab="datetime")
with(data1,{plot(data1$Sub_metering_1~data1$Datetime,ylab = "Energy sub metering",typ="l",xlab="")
  lines(Sub_metering_2~Datetime,col='Red')
  lines(Sub_metering_3~Datetime,col='Blue')})
legend("topright",col = c("black","red","blue"),lty = 1,lwd=2,legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data1$Datetime,data1$Global_reactive_power,type="l", ylab="Global_reactive_power", xlab="")
dev.off()